declare module "react-icons/fi";
declare module "react-icons/fa";
declare module "react-icons/md";
declare module "react-icons/ri";
declare module "react-icons/bi";
declare module "react-icons/ai";
declare module "react-icons/bs";
declare module "react-icons/hi";
declare module "react-icons/*";
